-- SQL for Supabase Setup

-- 1. Threads Table (Conversation History)
CREATE TABLE threads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  whatsapp_number TEXT UNIQUE NOT NULL,
  agent_type TEXT DEFAULT 'support',
  history JSONB DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Leads Table
CREATE TABLE leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  email TEXT,
  phone TEXT,
  status TEXT DEFAULT 'New',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Settings Table
CREATE TABLE settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tasks Table
CREATE TABLE tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'pending', -- pending, in-progress, completed
  priority TEXT DEFAULT 'medium', -- low, medium, high
  assigned_agent TEXT, -- sales, marketing, support
  created_at TIMESTAMPTZ DEFAULT NOW()
);
