-- SQL for Supabase Setup

-- 1. Threads Table (Conversation History)
CREATE TABLE threads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  whatsapp_number TEXT UNIQUE NOT NULL,
  agent_type TEXT DEFAULT 'support',
  history JSONB DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Leads Table
CREATE TABLE leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  email TEXT,
  phone TEXT,
  status TEXT DEFAULT 'New',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Settings Table
CREATE TABLE settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Initial Prompts
INSERT INTO settings (key, value) VALUES ('prompts', '{
  "sales": "You are a persuasive sales agent for Ansury. Your goal is to qualify leads and book meetings using the book_meeting tool.",
  "marketing": "You are a creative marketing expert. Explain the benefits of AI automation to the user.",
  "support": "You are a helpful customer support agent. Answer questions about Ansury services."
}');
